// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmI39rxAE5iS53QGj6jZFNhFW3QsZgmaM',
    appId: '1:434236324879:web:028645f9e942580602377a',
    messagingSenderId: '434236324879',
    projectId: 'peto-d8c1b',
    authDomain: 'peto-d8c1b.firebaseapp.com',
    storageBucket: 'peto-d8c1b.firebasestorage.app',
    measurementId: 'G-T4H1GNRGSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXFZPZEy6F7xPEWa3NLVN8by1_OOxUW4',
    appId: '1:670284790176:android:019bc143bc12080712ccc5',
    messagingSenderId: '670284790176',
    projectId: 'hopeshore-20d85',
    storageBucket: 'hopeshore-20d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC6engbGoPpSoIdIwGJjLnmY6ejWQW2NU',
    appId: '1:670284790176:ios:8f19a5f76cd0c04412ccc5',
    messagingSenderId: '670284790176',
    projectId: 'hopeshore-20d85',
    storageBucket: 'hopeshore-20d85.appspot.com',
    iosBundleId: 'com.jr.framguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsgeVrj6xXE6FNIGQT1FtOjNcOvkNishs',
    appId: '1:434236324879:ios:5eceab4a742cf98c02377a',
    messagingSenderId: '434236324879',
    projectId: 'peto-d8c1b',
    storageBucket: 'peto-d8c1b.firebasestorage.app',
    iosBundleId: 'com.example.peto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmI39rxAE5iS53QGj6jZFNhFW3QsZgmaM',
    appId: '1:434236324879:web:052cbcf8679d86c202377a',
    messagingSenderId: '434236324879',
    projectId: 'peto-d8c1b',
    authDomain: 'peto-d8c1b.firebaseapp.com',
    storageBucket: 'peto-d8c1b.firebasestorage.app',
    measurementId: 'G-XMSQLN9B4F',
  );
}